### ISSUE TITLE
Discord broke days-until

### ISSUE THREAD

**Issue by vilchu** [hummusbird/days-until#1]
Hello
Recent Discord update apparently broke the days-until plugin, and it won't change the status anymore.
Hope to get fix! 
Thank you!

**Comment by maeve-oake** [comment]
I've noticed! - the settings update stuff has changed endpoints and is also now protobuf.
Since powercord is EOL I'm trying to work with the Replugged team to sort this out :D

**Comment by maeve-oake** [comment]
all fixed!
